
channel_map:
  api: '#engineering'
  chef: '#sysops'
  crowdtilt-public-site: '#engineering'
  tilt-android: '#mobile'
  tilt-api-style-guide: '#engineering'
  tilt-images: '#engineering'
  tilt-nightwatch: '#engineering'
  tilt-open: '#engineering'
  vagrant: '#sysops'
  web: '#engineering'
