
channel_map:
  chef: '#sysops'
  crowdtilt-internal-api: '#engineering'
  crowdtilt-open-multisite: '#engineering'
  crowdtilt-public-site: '#engineering'
  site: '#engineering'
  tilt-android: '#mobile'
  tilt-api-style-guide: '#engineering'
  tilt-images: '#engineering'
  tilt-nightwatch: '#engineering'
  vagrant: '#sysops'
