channel_map:
  api: '#engineering'
  chef: '#sysops'
  tilt-android: '#mobile'
  crowdtilt-ios: '#mobile'
  tilt-api-style-guide: '#engineering'
  tilt-images: '#engineering'
  web-nightwatch: '#engineering'
  tilt-open: '#engineering'
  vagrant: '#sysops'
  web: '#engineering'
  web-dancer: '#engineering'
  ambassador-api: '#engineering'
  ambassador-web: '#engineering'
